export const sectors = [
  "-",
  "水産・農林",
  "卸売",
  "建設",
  "非鉄金属",
  "鉱業",
  "サービス",
  "不動産",
  "機械",
  "金属製品",
  "情報通信",
  "食料品",
  "医薬品",
  "陸運",
  "その他金融",
  "小売",
  "その他製品",
  "化学",
  "繊維製品",
  "電気機器",
  "ガラス土石",
  "証券・先物",
  "輸送用機器",
  "石油・石炭",
  "パルプ・紙",
  "精密機器",
  "ゴム製品",
  "鉄鋼",
  "銀行",
  "保険",
  "倉庫・運輸",
  "海運",
  "空運",
  "電気・ガス",
];

export const markets = [
  "-",
  "東証一部",
  "東証PR",
  "東証ST",
  "JQS",
  "JQG",
  "東証GR",
  "東証マザ",
  "東証二部",
  "名証MA",
  "名証セント",
  "名証NE",
  "札証",
  "名証二部",
  "福証",
  "札証アンビ",
  "福証QB",
  "名証一部",
  "名証PR",
  "東証",
];

export const sortTypes = [
  { value: "CODE", text: "銘柄コード" },
  { value: "MAX_CONSECUTIVE_PROFIT", text: "最大連続利益日数" },
  { value: "MAX_CONSECUTIVE_LOSS", text: "最大連続損失日数" },
  { value: "RECENT_CONSECUTIVES", text: "連続日数評価値" },
  { value: "TOTAL", text: "損益合計" },
  { value: "ABSOLUTE_TOTAL", text: "絶対損益合計" },
  { value: "TOTAL_PROFT", text: "利益合計" },
  { value: "TOTAL_LOSS", text: "損失合計" },
  { value: "CURRENT", text: "株価" },
  { value: "TOTAL_VOLUME", text: "出来高" },
];
